### ISSUE TITLE
Problem Selecting Region

### ISSUE THREAD

**Issue by faceoff34** [qdm12/private-internet-access-docker#1]
This script is a huge help, thanks for putting this together.   Everything was working fine until a few days ago.  Now, the only way I can get things to work is if I have my REGION=Germany.  If I change it to any other region (such as REGION=US Midwest in my case), I get an error message when I look in the docker PIA log:

> Starting Unbound to connect to Cloudflare DNS 1.1.1.1 at its TLS endpoint...DONE,
Starting OpenVPN using tcp with normal encryption,
Options error: Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: config (2.4.4),
Use --help for more information.
> 

when I run --help it returns this error:

> Wed Apr 18 02:09:29 2018 WARNING: cannot stat file '/auth.conf': No such file or directory (errno=2)
Options error: --auth-user-pass fails with '/auth.conf': No such file or directory (errno=2)
Options error: Please correct these errors.
Use --help for more information.
> 

Any idea on how to get this working?  Thanks!

**Comment by qdm12** [comment]
Thanks for your comment! 

You probably didn't mount `auth.conf` at the right place as it should now be at the root `/auth.conf` and no longer at `/pia/auth.conf` as before (recent updates I made).

Make sure you have the latest version as I've been reworking quite a bit these last 2-3 days. It's stable now.

```
docker pull qmcgaw/private-internet-access
```

I have tried with TCP normal in US West and it works for me. Let me know how it goes.

**Comment by faceoff34** [comment]
I deleted the container and image and tried to install/run again with the same error.  It works perfectly for region names that don't have a space.  Sweden, Netherlands, Singapore all work fine.  Any region that has a space in the name (US Midwest, UK London, AU Sydney) all give me the same error. 

I installed docker on a fresh machine and pulled the image and have the same problem.  It works with regions with no space and does not work with regions that have a space.

Below is my docker-compose.yml.  Like I said, before a few days ago, that same path form the auth.conf worked fine.

Thanks again for all your help!

```
version: "3"
services:

 pia:
    image: qmcgaw/private-internet-access
    container_name: pia
    cap_add:
     - NET_ADMIN
    devices:
     - /dev/net/tun
    networks:
     - pianet
    volumes:
     - /Users/faceoff34/Documents/auth.conf:/auth.conf:ro
    environment:
     - PROTOCOL=udp
     - ENCRYPTION=normal
     - REGION=US Midwest
    restart: always
        
networks:
    pianet:
        external: true

```
