### ISSUE TITLE
No DNS over Shadowsocks

### ISSUE THREAD

**Issue by Phorze** [qdm12/private-internet-access-docker#105]
I am not able to issue dns requests over UDP using shadowsocks, from the same subnet, using the EXTRA_SUBNETS variable. Curl'ing a webpage using the ip address does work. Consider the following logs:

```
shadowsocks:  2020-03-26 21:40:32 INFO: initializing ciphers... chacha20-ietf-poly1305
shadowsocks:  2020-03-26 21:40:32 INFO: using nameserver: 127.0.0.1
shadowsocks:  2020-03-26 21:40:32 INFO: tcp server listening at 0.0.0.0:8388
shadowsocks:  2020-03-26 21:40:32 INFO: udp server listening at 0.0.0.0:8388
....
shadowsocks:  2020-03-26 21:41:05 INFO: [8388] connect to www.youtube.com:443
shadowsocks:  2020-03-26 21:41:05 INFO: failed to lookup v6 address Could not contact DNS servers
shadowsocks:  2020-03-26 21:41:05 INFO: failed to lookup v4 address Could not contact DNS servers
```

using:
https://github.com/EasyPi/docker-shadowsocks-libev 
as client from the same docker host (udp enabled)

Then, to make sure i was using a supported client, installed and tried the android client mentioned in the docs. In the settings i enabled "Send DNS over UDP"

The following occurred:
```
shadowsocks:  2020-03-27 08:37:48 INFO: [udp] server receive a packet
shadowsocks:  2020-03-27 08:37:48 INFO: [8388] [udp] cache miss: dns.google:53 <-> 192.168.2.107:42370
shadowsocks:  2020-03-27 08:37:48 INFO: failed to lookup v4 address Could not contact DNS servers
shadowsocks:  2020-03-27 08:37:48 INFO: failed to lookup v4 address Could not contact DNS servers
shadowsocks:  2020-03-27 08:37:48 INFO: failed to lookup v6 address Could not contact DNS servers
```

Then, i changed the default dns in the android app from "dns.google" to "8.8.8.8" and things start working.
For now it seems relay only works if you set a dns server in the client. Will post back if this works with the easypi image.

**Comment by Phorze** [comment]
Turns out there is no way to set the DNS server. The author suggest using the following setup:

compose:
```
server:
  image: easypi/shadowsocks-libev
  ports:
    - "8388:8388/tcp"
    - "8388:8388/udp"
  environment:
    - METHOD=aes-256-cfb
    - PASSWORD=5ouMnqPyzseL
  restart: always

client:
  image: easypi/shadowsocks-libev
  command:
    ss-local -s 1.2.3.4
             -p 8388
             -m aes-256-cfb
             -k 5ouMnqPyzseL
             -b 0.0.0.0
             -l 1080
             -t 60
             --fast-open
  ports:
    - "1080:1080"
  restart: always

client-arm:
  image: easypi/shadowsocks-libev-arm
  ports:
    - "1080:1080"
  environment:
    - SERVER_ADDR=1.2.3.4
    - METHOD=aes-256-cfb
    - PASSWORD=5ouMnqPyzseL
  restart: always
```

Then test using curl:
```

  # On x86 server (1.2.3.4)
  $ docker-compose up -d server

  # On x86 client (192.168.1.234)
  $ docker-compose up -d client

  # On arm client (192.168.1.254)
  $ docker-compose up -d client-arm

  # On any LAN PC (192.168.1.XXX)
  $ curl -x socks5h://192.168.1.234:1080 https://www.youtube.com/
  $ curl -x socks5h://192.168.1.254:1080 https://www.youtube.com/
```

So it seems a shadowsocks server should be able to resolve DNS even if the client does not provide one.
