### ISSUE TITLE
Help: Getting 'connection reset by peer' error in a loop

### ISSUE THREAD

**Issue by FlorentLM** [qdm12/private-internet-access-docker#206]
**TLDR**: *Connection is dropped, sometimes minutes after being initiated, sometimes hours, with the following error in a loop (see log)*

1. Is this urgent?

    - [x] Yes
    - [ ] No

2. What VPN service provider are you using?

    - [x] PIA
    - [ ] Mullvad
    - [ ] Windscribe
    - [ ] Surfshark
    - [ ] Cyberghost

3. What's the version of the program?

    `Running version latest built on 2020-07-08T13:15:32Z (commit 3ae4523)`

4. What are you using to run the container?

    - [ ] Docker run
    - [x] Docker Compose
    - [ ] Kubernetes
    - [ ] Docker stack
    - [ ] Docker swarm
    - [ ] Podman
    - [ ] Other:

5. Extra information

Logs:

```log
...
2020-07-20T00:15:23.647+0200	ERROR	port forwarding: Get "http://209.222.18.222:2000/?client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx": read tcp 10.35.10.10:40102->209.222.18.222:2000: read: connection reset by peer
2020-07-20T00:15:23.647+0200	INFO	port forwarding: retrying in 5 seconds...
```

Configuration file:

```
version: '2'

services:
  gluetun:
    image: qmcgaw/private-internet-access
    container_name: gluetun
    hostname: gluetun
    networks:
      - vpn
    cap_add:
      - NET_ADMIN
    environment:
      - VPNSP=private internet access
      - PROTOCOL=udp
      - OPENVPN_VERBOSITY=1
      - OPENVPN_ROOT=no
      - TZ=xxxxxxxx/xxxxxxxxx

      # PIA
      - REGION=xxxxxxxxxxxxxx
      - USER=xxxxxxxxxxxxxxx
      - PASSWORD=xxxxxxxxxxxxx
      - PIA_ENCRYPTION=strong
      - PORT_FORWARDING=on
      - PORT_FORWARDING_STATUS_FILE=/forwarded_port

      # Others
      - IP_STATUS_FILE=/ip
      - EXTRA_SUBNETS=192.168.150.0/24

      - SHADOWSOCKS=off
      - TINYPROXY=off

    volumes:
      - /path/to/ip:/ip
      - /path/to/forwarded_port:/forwarded_port

    restart: always

```

Host OS: Debian 9
