### ISSUE TITLE
readme docker-compose questions

### ISSUE THREAD

**Issue by LunkSnee** [qdm12/private-internet-access-docker#21]
Using the readme docker-compose, I get the following error:
```
ERROR: Service 'deluge' uses the network stack of container 'pia' which does not exist.
```
It seems to be a problem due to the network stack not being up until the docker-compose finishes, but it won't finish until it finds the pia network stack. I had to break it into two docker-compose files to get it to successfully start and connect.

Additionally, should the hydra network_mode be "container:pia" or "container:hydra"?

**Comment by qdm12** [comment]
My bad I forgot a line `depends_on: pia` in the docker-compose.yml

It should be `network_mode: "container:pia"` for all containers you want to tunnel through the VPN. Simply add the depends_on line to all connected containers so that they wait for PIA container to launch.

I'll fix the readme soon, thanks for noticing that!

**Comment by braintapper** [comment]
I got the same error until I changed the line from `network_mode: "container:pia"` to `network_mode: "service:pia"`

**Comment by LunkSnee** [comment]
> I got the same error until I changed the line from `network_mode: "container:pia"` to `network_mode: "service:pia"`

That's correct braintapper, I have a single docker-compose file that works great for me, very different from the readme. It includes the right "network_mode" as you mention, and I'd recommend against the nginx approach to punching through - instead I like a socat docker container.

Sometime soon I hope to send qdm12 a full sample docker-compose file that he may want to consider recommending instead of what he has. The network_mode correction is the biggest to get right. Thanks for making sure this is corrected.

**Comment by qdm12** [comment]
Hi @LunkSnee I would be happy to test out the your docker compose! Please post a draft version of it here perhaps? Thanks for commenting!

**Comment by Nikola-K** [comment]
FWIW This is my docker compose, which seems to work, at least for me - of course there's custom stuff in there, which can be omitted but maybe it's useful to someone as-is:


```yaml
version: "3.1"

networks:
  downloads-public:
  downloads-vpn:

services:
  pia:
    build: https://github.com/qdm12/private-internet-access-docker.git
    image: qmcgaw/private-internet-access
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - USER=pNOPE
      - PASSWORD=hunter2
      - PROTOCOL=udp
      - ENCRYPTION=strong
      - REGION=Switzerland
      - EXTRA_SUBNETS=
      - NONROOT=no
      - BLOCK_MALICIOUS=off
      - BLOCK_NSA=off
      - UNBLOCK=
    volumes:
      - /home/nikola/containers/config/pia/auth.conf:/auth.conf
    networks:
      - downloads-vpn
    restart: always

  deluge:
    image: linuxserver/deluge
    network_mode: "service:pia"
    environment:
      - PUID=1000
      - PGID=997
      - TZ=Europe/Berlin
    volumes:
      - /home/nikola/containers/config/deluge:/config
      - /home/nikola/containers/storage/deluge:/downloads
      - /home/nikola/containers/storage/blackhole:/blackhole
      - /mnt/downloads/torrent_downloaded:/finished
    restart: unless-stopped
  
  nginx:
    image: nginx:alpine
    ports:
      - 8000:8000/tcp
    volumes:
      - /home/nikola/containers/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - downloads-vpn
    depends_on:
      - pia
      - deluge
```

and my nginx config

```
#nginx.conf
user nginx;
worker_processes 1;
events {
  worker_connections 64;
}
http {
  server {
    listen 8000;
    location / {
      proxy_pass http://pia:8112/;
      proxy_set_header X-Deluge-Base "/";
    }
  }
}
```

**Comment by qdm12** [comment]
Hey, thanks for sharing. I'll add a cleaner version to the readme. However beware i think you have your username and password in your environment variables, so please edit your message and reset your password on PIA. Hopefully you didn't get compromised yet!

**Comment by Nikola-K** [comment]
Thanks for the concern, but the username/password in the comment above are not real.

**Comment by LunkSnee** [comment]
Sorry for the delay, here is what I'm using.
The socat container can be duplicated however many times within the docker-compose.yml, for however many services you have inside PIA. 
For me, socat is just a lighter solution than running nginx. No external files needed, etc.

```
version: '3'

services:

  pia:
    image: qmcgaw/private-internet-access
    container_name: pia
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    networks:
      - default
    environment:
      - USER=file  # auth.conf, could also just define in .env ( ${USER} )
      - PASSWORD=file   # auth.conf, could also just define in .env ( ${PW} )
      - PROTOCOL=udp
      - ENCRYPTION=strong
      - BLOCK_MALICIOUS=on
      - REGION=Switzerland
      - EXTRA_SUBNETS=
      - NONROOT=no
#    ports:          # mapping service ports here doesn't work, use socat
    volumes:
      - ./auth.conf:/auth.conf:ro
    restart: always

  whoami:  # using whoami here, but could be any container
    container_name: pia-whoami
    image: containous/whoami # A container that exposes an API to show its IP address
    restart: unless-stopped
    network_mode: "service:pia"
#    ports:          # would be port 80, but mapping port has to go through socat, piercing vpn 

  socat0:
    image: alpine/socat
    container_name: socat0
    depends_on:
      - pia
      - whoami
    ports:
      - 10002:10002/tcp  # external port for whoami container access
    command: tcp-listen:10002,fork,reuseaddr tcp-connect:pia:80
    restart: always
```
