### ISSUE TITLE
EXTRA_SUBNETS not working

### ISSUE THREAD

**Issue by johnpyp** [qdm12/private-internet-access-docker#22]
Hello,

I'm trying to use EXTRA_SUBNETS to access the container via my local network. Here is my docker-compose file I'm working with:

```
  pia:
    image: qmcgaw/private-internet-access:latest
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    restart: unless-stopped
    ports:
      - 8113:8113
    environment:
      - USER=${PIA_USER}
      - PASSWORD=${PIA_PASS}
      - PROTOCOL=udp
      - ENCRYPTION=strong
      - REGION=${PIA_REGION}
      - EXTRA_SUBNETS=192.168.1.0/24
      - NONROOT=
    labels:
      <<: *default_traefik_opts
      traefik.backend: pia
      traefik.port: 8113
      traefik.local.frontend.rule: 'Host:qbit.localhost'
      traefik.https.frontend.rule: 'Host.qbit.${DOMAIN:-default}'
```
I'm trying to access it via `192.168.1.11:8113`, as I need it to be accessible via that as well as my reverse proxy (traefik). I get a connection refused whenever trying to connect via ip, unfortunately.
