### ISSUE TITLE
Troubles with accessing a port of a container using caddy scratch

### ISSUE THREAD

**Issue by fester88** [qdm12/private-internet-access-docker#25]
Hi,

I've been trying to follow the documentation in the README under "Access ports of containers connected to PIA" heading, but so far have had no luck. It starts up OK, however trying to access Deluge's web UI on port 8112 only returns a "502 Bad Gateway" error.

Here is my Caddyfile:
```
:8112 {
    proxy / deluge:8112
}
```

And here is my docker-compose.yml:
```
version: "3.6"
services:

  pia:
    build: https://github.com/qdm12/private-internet-access-docker.git
    image: qmcgaw/private-internet-access
    container_name: pia
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    network_mode: bridge
    environment:
      - USER=XXX
      - PASSWORD=XXX
      - PROTOCOL=udp
      - ENCRYPTION=strong
      - REGION=XXX
      - EXTRA_SUBNETS=
      - NONROOT=no
      - BLOCK_MALICIOUS=off
      - BLOCK_NSA=off
      - UNBLOCK=
    restart: always

  piaproxy:
    image: qmcgaw/caddy-scratch
    container_name: piaproxy
    ports:
      - 8112:8112/tcp
    external_links:
      - pia:deluge
    volumes:
      - ./Caddyfile:/Caddyfile:ro

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    depends_on:
      - pia
    network_mode: "service:pia"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - deluge-config:/config
      - deluge-downloads:/downloads
    restart: always

volumes:
  deluge-config:
  deluge-downloads:
```

Any help, tips or witty insults would be greatly appreciated!

**Comment by qdm12** [comment]
Hi there,

Usually 502 means it cannot find Deluge. Maybe try with `network_mode: "container:pia"` instead of `"network_mode: "service:pia"`? It seems that's the only difference between my config and yours.

For your information, my Caddyfile is

```ruby
:8112 {
    redir /deluge /deluge/ 307
    proxy /deluge http://deluge:8112 {
        transparent
        without /deluge
        header_upstream X-Deluge-Base "/deluge"
    }
}
```

so that I can access it at `localhost:8112/deluge` (I use another proxy on top - nothing to do with the vpn - so it's a nice https://domainname/deluge access for the web ui)

Let me know how it goes!

**Comment by fester88** [comment]
Hi and thanks for the speedy reply,

I've tried changing it to container network mode, but even with depends_on being set to the pia container, it still reports the error:

```
ERROR: Service 'deluge' uses the network stack of container 'pia' which does not exist.
```

Today I tried the same docker-compose and Caddyfile pasted above on a separate machine and found that it still reports the 502 error when accessing http://localhost:8112/.

I also tried removing the piaproxy service and setting the deluge network_mode to host just to confirm if  the deluge service was working, and was able to access the UI at port 8112 fine.

I'll have a try at implementing your Caddyfile next and let you know how I go.

**Comment by qdm12** [comment]
Hi, sorry for the late reply.

You would have to start the PIA container first and wait a few seconds. This is due to the fact `depends_on` only waits a few milliseconds and not until the network stack of pia is launched.

```sh
docker-compose down
docker-compose up -d pia
```

You can then launch the other containers `docker-compose up -d`

**Comment by fester88** [comment]
Hi,

I tried separating them out into different compose files, and whilst it works with the container network mode, I'm still unable to connect to Deluge at http://X.X.X.X/deluge. The browser throws a ERR_CONNECTION_REFUSED error. 

My Caddyfile:
```
:8112 {
    redir /deluge /deluge/ 307
    proxy /deluge http://deluge:8112 {
        transparent
        without /deluge
        header_upstream X-Deluge-Base "/deluge"
    }
}
```

My docker-compose-pia.yml:
```
version: "3.6"

services:
  pia:
    build: https://github.com/qdm12/private-internet-access-docker.git
    image: qmcgaw/private-internet-access
    container_name: pia
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    network_mode: bridge
    environment:
      - USER=XXX
      - PASSWORD=XXX
      - PROTOCOL=udp
      - ENCRYPTION=strong
      - REGION=XXX
      - EXTRA_SUBNETS=
      - NONROOT=no
      - BLOCK_MALICIOUS=off
      - BLOCK_NSA=off
      - UNBLOCK=
    restart: always
```

My docker-compose.yml:
```
version: "3.6"

services:
  piaproxy:
    image: qmcgaw/caddy-scratch
    container_name: piaproxy
    ports:
      - 8112:8112/tcp
    external_links:
      - pia:deluge
    volumes:
      - ./Caddyfile:/Caddyfile:ro

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: "container:pia"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - deluge-config:/config
      - deluge-downloads:/downloads
    restart: always

volumes:
  deluge-config:
  deluge-downloads:
```

I'm launching the docker-compose-pia 10 seconds before the other docker compose file.

I'm not sure if this would have an impact, however I am running docker on an Ubuntu Sever machine attached to my LAN and trying to access the URLs from my workstation. I've been able to run other containers like Portainer and connect to them from my workstation without issues.

**Comment by fester88** [comment]
Would I need to wait until the pia container has finished its health check before trying to access the deluge UI, or should it not matter?

**Comment by qdm12** [comment]
Hi there,

Try at `http://xx.xx.xx.xx:8112/deluge`.
If you want to access it without `8112`, change the port mapping to `80:8112`.

The healthcheck is independent, you don't need to wait for it. You just need to wait for it to connect to PIA servers `Initialization completed` as I recall, which takes 2-5 seconds usually. I'm researching how to make a container wait x seconds in a docker compose file but I don't think it's possible unfortunately.

Let me know if it works out!

**Comment by qdm12** [comment]
Hi,

Actually you can make it wait for a successful healthcheck in docker-compose using for example:

```yml
depends_on:
  pia:
    condition: service_healthy
```

Maybe that would solve the problem to have all your services in the same docker-compose.yml file 👍

**Comment by fester88** [comment]
Hi, thanks for helping me with this.

Unfortunately, still no luck. Using the same compose files I posted last, http://X.X.X.X:8112/deluge reports a "502 Bad Gateway" error.

The condition option for depends_on looks handy, but is no longer supported in v3 of the compose files. Should I perhaps try reverting back to v2 and see if it works?

**Comment by qdm12** [comment]
Hi @fester88, sorry for the long delay. So I have re-explored docker-compose mechanisms etc for networking. I believe the error on your side was because piaproxy (some docker-compose created network) was in another network than pia (bridge).

Anyway I solved other problems you had including the ugly `depends_on`, you should use `service` instead which allows to launch all containers from one compose file without any problem 👍 

I tweaked the Caddyfile to use port 8080, mapped to port 80 (HTTP) on your host so that you can access it with *http://yourhostnameorip/deluge* directly without specifying the port.

The Caddyfile:

```ruby
:8080 {
    redir /deluge /deluge/ 307
    proxy /deluge http://deluge:8112 {
        transparent
        without /deluge
        header_upstream X-Deluge-Base "/deluge"
    }
}
```

The docker-compose.yml

```yml
version: '3'
services:
  pia:
    image: qmcgaw/private-internet-access
    container_name: pia
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    network_mode: bridge
    environment:
      - USER=XXX
      - PASSWORD=XXX
      - PROTOCOL=udp
      - ENCRYPTION=strong
      - REGION=XXX
      - EXTRA_SUBNETS=
      - NONROOT=no
      - BLOCK_MALICIOUS=off
      - BLOCK_NSA=off
      - UNBLOCK=
    restart: always
  piaproxy:
    image: qmcgaw/caddy-scratch
    container_name: piaproxy
    network_mode: bridge
    external_links:
      - pia:deluge
    ports:
      - 80:8080/tcp
    volumes:
      - ./Caddyfile:/Caddyfile:ro
    restart: always
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: "service:pia"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - deluge-config:/config
      - deluge-downloads:/downloads
    restart: always

volumes:
  deluge-config:
  deluge-downloads:
```

I did not test it but it should 98% chance work properly this time. Thanks !

**Comment by fester88** [comment]
Hi,

It works! Thanks again for all your help with this.

I did still have to add depends_on as when starting up it couldn't find the pia service without it.

For reference, the Caddyfile you posted above worked perfectly with this docker-compose.yml:

```
version: '3'
services:
  pia:
    image: qmcgaw/private-internet-access
    container_name: pia
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    network_mode: bridge
    environment:
      - USER=XXX
      - PASSWORD=XXX
      - PROTOCOL=udp
      - ENCRYPTION=strong
      - REGION=XXX
      - EXTRA_SUBNETS=
      - NONROOT=no
      - BLOCK_MALICIOUS=off
      - BLOCK_NSA=off
      - UNBLOCK=
    restart: always

  piaproxy:
    image: qmcgaw/caddy-scratch
    container_name: piaproxy
    network_mode: bridge
    depends_on:
      - pia
    external_links:
      - pia:deluge
    ports:
      - 80:8080/tcp
    volumes:
      - ./Caddyfile:/Caddyfile:ro
    restart: always

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: "service:pia"
    depends_on:
      - pia
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - deluge-config:/config
      - deluge-downloads:/downloads
    restart: always

volumes:
  deluge-config:
  deluge-downloads:
```

Next I'll have a stab at a PR to update the README docs with what worked for me to help others.

Thanks @qdm12
