### ISSUE TITLE
Mapped ports only available to localhost now?

### ISSUE THREAD

**Issue by coreshift** [qdm12/private-internet-access-docker#47]
Maybe it's just me, but I was exposing ports in the PIA docker-compose file for other services that rely on it. Now those ports only seem available on localhost. Did something change?

**Comment by qdm12** [comment]
Hi there!

Are you exposing or publishing ports? Would you mind sharing your docker-compose (take care to remove credentials)?

Nothing changed as far as I can tell. I have however made several changes today so maybe try `docker pull qmcgaw/private-internet-access` to get the latest version?

**Comment by coreshift** [comment]
The compose file is identical to the one in the repo with the notable exceptions being different username and password and one additional port for mysql. I also had to add a shadowsocks password to get it to run.

[mysql-docker-compose.yml.txt](https://github.com/qdm12/private-internet-access-docker/files/3593426/mysql-docker-compose.yml.txt)

[pia-docker-compose.yml.txt](https://github.com/qdm12/private-internet-access-docker/files/3593424/pia-docker-compose.yml.txt)

**Comment by coreshift** [comment]
Oops. Accidentally closed this.

**Comment by coreshift** [comment]
I've been trying to create a LAN behind PIA using iptables, not your Docker, although it would be great if I could use it for that purpose. Could that be causing problems? Can't imagine why. Would iptables -F screw things up?

**Comment by qdm12** [comment]
Ok so I removed the silly requirements of having to set the shadowsocks password if it's off, sorry about that.

Maybe my documentation is wrong, as I recall it needed a reverse proxy connected to PIA to access ports of containers connected with `"container:pia"`.
A solution you could try that currently works for me is to have all your PIA related services in the same docker-compose file, see the instructions for *Access ports of containers connected to PIA, all in the same docker-compose.yml*.

It should look like:

```yml
version: "3"
services:
  pia:
    image: qmcgaw/private-internet-access
    container_name: pia
    init: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - USER=js89ds7
      - PASSWORD=8fd9s239G
    ports:
      - 3306:3306/tcp
  mysql:
    image: mysql/mysql-server:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=x
    volumes:
      - ./MySQL/var/lib/mysql:/var/lib/mysql
      - ./MySQL/etc/my.cnf:/etc/my.cnf
      - ./MySQL/etc/my.cnf.d:/etc/my.cnf.d
    restart: always
    network_mode: "service:pia"
```
