### ISSUE TITLE
New version of the image stopped working

### ISSUE THREAD

**Issue by lamarios** [qdm12/private-internet-access-docker#48]
The new version ( released on the 10th of September) broke my set up and is not working anymore.

The logs don't show much so I'm not sure what to do.

```yaml
pia:
  image: qmcgaw/private-internet-access
  container_name: pia
  restart: always
  cap_add:
   - NET_ADMIN
  init: true
  devices:
   - /dev/net/tun
  ports:
   - "9091:9091"  // web ui of other container
   - "8989:8989"  // web ui of other container
   - "7878:7878"  // web ui of other container
   - "9999:9999" // only port forwarded
   - "9999:9999/udp" //only port forwared
   - "9117:9117/tcp" // web ui of other container
  volumes:
   - /etc/localtime:/etc/localtime:ro
  environment:
   USER: myusername
   PASSWORD: mypassword
   PROTOCOL: udp
   ENCRYPTION: strong
   REGION: Singapore
   EXTRA_SUBNETS: 192.168.1.0/24

```

and the logs:
```
 =========================================
 =========================================
 ============= PIA CONTAINER =============
 =========================================
 =========================================
 == by github.com/qdm12 - Quentin McGaw ==

OpenVPN version: 2.4.7
Unbound version: 1.9.1
Iptables version: v1.8.3
TinyProxy version: 1.10.0
ShadowSocks version: 3.3.1
SHADOWSOCKS_PASSWORD is not set
```

Is there a way to get more information ?

**Comment by qdm12** [comment]
Hi there,

I fixed it a few hours ago, sorry about it.

It's because there is a new environment variable `SHADOWSOCKS_PASSWORD` to use a Shadowsocks socks5 proxy server. I made it compulsory by mistake, it's now only required if `SHADOWSOCKS=on`.

Please update the image

```sh
docker pull qmcgaw/private-internet-access
```

I am also working on a release system so that you could use Docker Hub tags to fallback to a previous version, I'll comment here once it's up.

**Comment by gurabli** [comment]
Great work, again!
The fallback would be really appreciated, as we already discussed few weeks ago. I use your container also on daily basis, and it is sometimes not good to loose functionality after a new update.
Thanks!

**Comment by qdm12** [comment]
I'll update the readme to have a manual way to re-build the image yourself for now. It will consist pretty much of a git clone of the repository, then a reset to a certain commit and then a `docker build`.

Hopefully I can setup that release system soon as well.

**Comment by gurabli** [comment]
That sounds really good.
Btw, I wanted to ask you if you would like to include your docker container to Pgblitz? Don't want to smap this thread, maybe discuss in another or in private?

**Comment by gurabli** [comment]
That sounds really good.
Btw, I wanted to ask you if you would like to include your docker container to Pgblitz? Don't want to smap this thread, maybe discuss in another or in private?

**Comment by lamarios** [comment]
For some reasons the shadowsocks parameters are still required for me even after a pull.

By the way, the documentation about port forwarding is a bit confusing. The environment variable table show "on" and "off" for PORT_FORWARDING and the documentation below it and the Dockerfile are using boolean.

**Comment by qdm12** [comment]
I added how to build the image for a previous commit in the Troubleshooting section.

The other issues should be fixed now, thanks a lot for letting me know I didn't spot them (cannot really unit test these unfortunately).

**Comment by juan11perez** [comment]
@lamarios 
Would you mind sharing the docker-compose configuration of one of the containers you list under ports as "   - "9091:9091"  // web ui of other container". I've been struggling with this set up. 
Thank you

**Comment by lamarios** [comment]
```yaml
pia:
  image: qmcgaw/private-internet-access
  container_name: pia
  restart: always
  cap_add:
    - NET_ADMIN
  init: true
  devices:
    - /dev/net/tun
  ports:
    - "9091:9091" #transmission web ui
    - "8989:8989"  #sonarr web ui
    - "7878:7878" #radarr web ui
    - "9999:9999" #transmission seeding port
    - "9999:9999/udp" #transmission seeding port
    - "9117:9117/tcp" # jackett web ui
  volumes:
    - /etc/localtime:/etc/localtime:ro
  environment:
    USER: mysuperuser
    PASSWORD: mysuperpassword
    PROTOCOL: udp
    ENCRYPTION: strong
    PORT_FORWARDING: "true"
    REGION: Singapore
    EXTRA_SUBNETS: 192.168.1.0/24
    SHADOWSOCKS: "off"
    SHADOWSOCKS_PASSWORD: ""

#######
## Torrent related containers, neeeds to go through VPN
#######
sonarr:
  container_name: sonarr
  image: linuxserver/sonarr
  restart: always
  network_mode: "service:pia"
  volumes:
    - ./Sonarr/appdata:/config
    - /mnt/pool/media/Series:/tv
    - /mnt/pool/media/Downloads:/downloads
    - /etc/localtime:/etc/localtime:ro
  environment:
    PUID: 1000
    PGID: 1000
radarr:
  container_name: radarr
  image: linuxserver/radarr
  restart: always
  network_mode: "service:pia"
  volumes:
    - ./radarr/:/config
    - /mnt/pool/media/Movies:/movies
    - /mnt/pool/media/Downloads:/downloads
    - /etc/localtime:/etc/localtime:ro
  environment:
    PUID: 1000
    PGID: 1000
jackett:
  container_name: jackett
  image: linuxserver/jackett
  restart: always
  network_mode: "service:pia"
  volumes:
    - ./jackett/config:/config
  environment:
    PUID: 1000
    PGID: 1000
####################
##### Transmission
####################
transmission:
  container_name: transmission
  image: linuxserver/transmission
  network_mode: "service:pia"
  restart: always
  depends_on:
    - pia
  volumes:
    - ./transmission/config:/config
    - /mnt/pool/media/Downloads:/downloads
    - /etc/localtime:/etc/localtime:ro
    - /mnt/pool/media/to-process/torrent:/watch
  environment:
    PUID: 1000
    PGID: 1000
#######
## end of torrent related stuff
#######
```

I"m not sure how it works but instead of setting up "ports" on the containers using the VPN (radarr, sonarr etc) just set it up on the PIA container and it just works.
