### ISSUE TITLE
Default install instructions don't work

### ISSUE THREAD

**Issue by derekslenk** [qdm12/private-internet-access-docker#61]
The run command on the dockerhub page isn't sufficient to start the container. I was getting errors with IPTABLES and not being ran as root.

The minimum compose I needed was:

```yml
  private-internet-access:
      container_name: pia
      cap_add:
        - NET_ADMIN
      devices:
        - /dev/net/tun
      network_mode: bridge
      # init: true - doesn't work on 3.3
      environment:
          - REGION=CA Montreal
          - USER=p1234431
          - PASSWORD=nonono!
          - NONROOT=no
      image: qmcgaw/private-internet-access
```
