### ISSUE TITLE
Cannot Access container on local ip.

### ISSUE THREAD

**Issue by calgara12** [qdm12/private-internet-access-docker#89]
Hey, 

I would like to start by thanking you for writing this, however i'm struggling to get it to work.
I want to to run jlesage/jdownloader2 behind your private-internet-access-docker.

Here is my docker-compose file:
```
version: '3.7'
services:
  pia:
    image: qmcgaw/private-internet-access
    container_name: pia
    init: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - USER=secretuser
      - PASSWORD=secretpassw
      - PROTOCOL=tcp
    ports:
      - 5800:5800/tcp
  jdownloaderPIA:
    image: jlesage/jdownloader-2:latest
    container_name: jdownloaderPIA
    network_mode: "service:pia"
    environment:
     - PGID=1000
     - PUID=1000
     - TZ=Europe/Vienna
     - VNC_PASSWORD=somepw
    volumes:
     - jdownloaderPIA_config:/config
volumes:
  jdownloaderPIA_config:
    driver: local
```

Do you know what I'm doing wrong here?
When i visit 192.168.178.100:5800 I get a timeout.

Any help is greatly appreciated. Thanks! :)
